print("Hello World")

# The function is saving the input response
input("Enter your name: ")
print("Hello" + input("Enter your city:") + "!")


# In this line, I took the name and counted the number of characters
print(len(input("What is your name?")))

# Now I did the step by step, got the name, counted the number of characters and showed the number
username = input("What is your name")
length = len(username)
print(length)


#New lines can be created with a \ and the letter n
print("Hello" + " World" + "\n2")  



